spring:
  datasource:
    url: jdbc:mysql://localhost:3306/yourssu?serverTimezone=Asia/Seoul
    username: bfly
    password: 20203085
    driver-class-name: com.mysql.cj.jdbc.Driver

  sql:
    init:
      mode: always

  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    open-in-view: true

    hibernate:
      ddl-auto: none

    properties:
      hibernate:
        format_sql: true
        default_batch_fetch_size: 500

logging:
  level:
    org:
      hibernate:
        SQL: debug